name: logo timely update

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
    - uses: actions/checkout@master
      name: Check out code  
    
    - name: update logo
      run: |  
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "xxx@websoft9.com"
        files=$(ls /)
        str=".png"
        for file in ${files};do
          echo $file
          if [[ $file =~ $str ]];then
            echo $file
            git rm $file
            git commit -m "delete"
          fi
        done
        git push -u
