name: logo timely update

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
    - uses: actions/checkout@master
      name: Check out code  
    
    - name: update logo
      run: |
        files=$(ls appmanage/static/images)
        for file in $files;do
          app=$(echo ${file%%-*})
          entry=$(curl --include \
                       --request GET \
                       --header 'Authorization: Bearer ${{secrets.CONTENTFUL}}' \
                       https://api.contentful.com/spaces/wbgvl9e8pqe2/environments/master/entries?content_type=media\&fields.slug=${app} | tail -n 1)
          data=$(echo $entry | jq -r '.items[0].fields.imageurl')
          if [[ "$data" == null ]];then
              continue
          fi
          url=$(echo $data | sed 's/en-US/en/' | jq -r '.en')

          logoFile=appmanage/static/images/${app}-websoft9.png
          rm -f $logoFile
          
          wget -P appmanage/static/images $url
          
          git rm --cached $logoFile

          break
        done
        
    - name: push logo
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update logo
