name: logo timely update

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
    - uses: actions/checkout@master
      name: Check out code  
    
    - name: update logo
      run: |  
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "xxx@websoft9.com"
        
        # 获取contentful中所有url
        entry=$(curl --include \
             --request GET \
             --header 'Authorization: Bearer ${{secrets.CONTENTFUL}}' \
             https://api.contentful.com/spaces/wbgvl9e8pqe2/environments/master/entries?content_type=media\&locale=en-US\&select=fields.imageurl |tail -n 1)
        echo $entry
        total=$(echo $entry | jq '.total')
        for ((i=0; i<${total}; i ++));do
            data=$(echo $entry | jq '.items[0]')
            echo $data
            echo $data | sed 's/en-US/en/'
            url=$(echo $data | sed 's/en-US/en/' | jq -r '.fields.imageurl.en')
            echo $url
            file=$(echo appmanage/static/images/${url##*/})
            echo $file
            
            if [[ -e ${file} ]];then
              git rm $file
              git commit -m "delete former logo"
            fi
            wget -P appmanage/static/images $url  
            
            break
        done
        
        
    - name: push logo
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update logo
