name: logo timely update

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
    - uses: actions/checkout@master
      name: Check out code  
    
    - name: update logo
      run: |  
        # 获取contentful中所有url
        entry=$(curl --include \
             --request GET \
             --header 'Authorization: Bearer ${{secrets.CONTENTFUL_TOKEN}}' \
             https://api.contentful.com/spaces/wbgvl9e8pqe2/environments/master/entries?content_type=media\&locale=en-US\&select=fields.imageurl)
        echo $entry
        
